'use client';

import { useWorkflowStore } from '@/lib/stores/workflow-store';
import { cn } from '@/lib/utils/cn';
import {
  AlertCircle,
  CheckCircle,
  FileText,
  HelpCircle,
  Image,
  Mail,
  Paperclip,
  Send,
  X,
} from 'lucide-react';
import React, { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';

interface WorkflowHelpModalProps {
  readonly isOpen: boolean;
  readonly onClose: () => void;
}

interface SupportTicket {
  readonly subject: string;
  readonly description: string;
  readonly priority: 'low' | 'medium' | 'high' | 'critical';
  readonly category: 'bug' | 'feature' | 'question' | 'documentation';
  readonly attachments: File[];
  readonly userInfo: {
    readonly workflowName?: string;
    readonly nodeCount: number;
    readonly edgeCount: number;
    readonly browserInfo: string;
  };
}

export function WorkflowHelpModal({
  isOpen,
  onClose,
}: Readonly<WorkflowHelpModalProps>): React.JSX.Element | null {
  const { activeWorkflow, nodes, edges } = useWorkflowStore();

  const [subject, setSubject] = useState('');
  const [description, setDescription] = useState('');
  const [priority, setPriority] = useState<SupportTicket['priority']>('medium');
  const [category, setCategory] = useState<SupportTicket['category']>('question');
  const [attachments, setAttachments] = useState<File[]>([]);
  const [isSending, setIsSending] = useState(false);
  const [sendStatus, setSendStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [errorMessage, setErrorMessage] = useState('');

  const fileInputRef = React.useRef<HTMLInputElement>(null);

  // Handle keyboard shortcuts (especially Escape key)
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        onClose();
      }
    };

    if (isOpen) {
      document.addEventListener('keydown', handleKeyDown);
    }

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files || []);
    setAttachments(prev => [...prev, ...files]);
    // Reset input to allow selecting the same file again
    if (event.target) {
      event.target.value = '';
    }
  };

  const removeAttachment = (index: number) => {
    setAttachments(prev => prev.filter((_, i) => i !== index));
  };

  const formatFileSize = (bytes: number): string => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  const getFileIcon = (file: File) => {
    if (file.type.startsWith('image/')) {
      return Image;
    }
    return FileText;
  };

  const getBrowserInfo = (): string => {
    const nav = navigator;
    return `${nav.userAgent} | Screen: ${screen.width}x${screen.height} | Language: ${nav.language}`;
  };

  const handleSendSupport = async () => {
    if (!subject.trim() || !description.trim()) {
      setErrorMessage('Please fill in both subject and description fields.');
      return;
    }

    setIsSending(true);
    setSendStatus('idle');
    setErrorMessage('');

    try {
      // Prepare support ticket data
      const supportTicket: SupportTicket = {
        subject: subject.trim(),
        description: description.trim(),
        priority,
        category,
        attachments,
        userInfo: {
          workflowName: activeWorkflow?.name || 'No workflow loaded',
          nodeCount: nodes.length,
          edgeCount: edges.length,
          browserInfo: getBrowserInfo(),
        },
      };

      // Prepare email content
      const emailContent = `
PLC-GBT Workflow Help Request

Subject: ${supportTicket.subject}
Priority: ${supportTicket.priority.toUpperCase()}
Category: ${supportTicket.category.toUpperCase()}

Description:
${supportTicket.description}

System Information:
- Workflow: ${supportTicket.userInfo.workflowName || 'None'}
- Nodes: ${supportTicket.userInfo.nodeCount}
- Connections: ${supportTicket.userInfo.edgeCount}
- Browser: ${supportTicket.userInfo.browserInfo}
- Timestamp: ${new Date().toISOString()}

Attachments: ${supportTicket.attachments.length} file(s)
${supportTicket.attachments.map(f => `- ${f.name} (${formatFileSize(f.size)})`).join('\n')}

---
Generated by PLC-GBT Workflow Management UI
      `.trim();

      // Send email via backend API that uses MCP email service
      const response = await fetch('/api/v1/support/send-email', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          to: 'plc-gbt-support@whiskeyhouse.com',
          subject: `[PLC-GBT Workflow] ${supportTicket.subject}`,
          text: emailContent,
          html: emailContent.replace(/\n/g, '<br>'),
          priority: supportTicket.priority,
          category: supportTicket.category,
          // Note: File attachments will be handled separately due to size limitations
          attachmentCount: supportTicket.attachments.length,
          attachmentNames: supportTicket.attachments.map(f => f.name),
        }),
      });

      if (!response.ok) {
        throw new Error(`Failed to send email: ${response.status} ${response.statusText}`);
      }

      const result = await response.json();
      console.log('Support email sent successfully:', result);

      setSendStatus('success');

      // Auto-close after success
      setTimeout(() => {
        onClose();
        // Reset form
        setSubject('');
        setDescription('');
        setPriority('medium');
        setCategory('question');
        setAttachments([]);
        setSendStatus('idle');
      }, 2000);
    } catch (error) {
      console.error('Failed to send support email:', error);
      setSendStatus('error');
      setErrorMessage(error instanceof Error ? error.message : 'Failed to send support email');
    } finally {
      setIsSending(false);
    }
  };

  // Priority colors for visual styling (commented out to resolve linting warning)
  // const priorityColors = {
  //   low: 'bg-green-500/20 text-green-400 border-green-500/30',
  //   medium: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
  //   high: 'bg-orange-500/20 text-orange-400 border-orange-500/30',
  //   critical: 'bg-red-500/20 text-red-400 border-red-500/30',
  // };

  const categoryIcons = {
    bug: '🐛',
    feature: '✨',
    question: '❓',
    documentation: '📚',
  };

  return createPortal(
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={onClose}
        onKeyDown={e => {
          if (e.key === 'Escape') {
            onClose();
          }
        }}
        role="button"
        tabIndex={0}
        aria-label="Close modal"
      />

      {/* Modal */}
      <div className="relative bg-[#2d2d2d] border border-[#404040] rounded-lg shadow-2xl w-full max-w-2xl mx-4 max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-[#404040] bg-[#252526]">
          <div className="flex items-center gap-3">
            <HelpCircle className="w-5 h-5 text-blue-400" />
            <h2 className="text-lg font-semibold text-white">PLC-GBT Workflow Help</h2>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-gray-400 hover:text-white hover:bg-[#3d3d3d] rounded transition-colors"
            aria-label="Close help modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto max-h-[calc(90vh-120px)]">
          {sendStatus === 'success' ? (
            <div className="text-center py-8">
              <CheckCircle className="w-16 h-16 text-green-400 mx-auto mb-4" />
              <h3 className="text-xl font-semibold text-white mb-2">Support Request Sent!</h3>
              <p className="text-gray-400">
                Your help request has been sent to our support team. You should receive a response
                within 24 hours.
              </p>
            </div>
          ) : (
            <form
              onSubmit={e => {
                e.preventDefault();
                handleSendSupport();
              }}
              className="space-y-6"
            >
              {/* Quick Help Section */}
              <div className="bg-[#1e1e1e] border border-[#404040] rounded-lg p-4">
                <h3 className="text-sm font-semibold text-white mb-2 flex items-center gap-2">
                  <HelpCircle className="w-4 h-4" />
                  Quick Help
                </h3>
                <div className="text-xs text-gray-400 space-y-1">
                  <p>
                    • <strong>Tooltips:</strong> Hover over any button for help
                  </p>
                  <p>
                    • <strong>Modals:</strong> Click outside or press Escape to close
                  </p>
                  <p>
                    • <strong>Zoom:</strong> Use mouse wheel or toolbar buttons
                  </p>
                  <p>
                    • <strong>Nodes:</strong> Drag from palette or double-click to configure
                  </p>
                </div>
              </div>

              {/* Support Request Form */}
              <div className="space-y-4">
                <h3 className="text-sm font-semibold text-white">Contact Support</h3>

                {/* Category and Priority */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label
                      htmlFor="help-category"
                      className="block text-xs font-medium text-gray-300 mb-2"
                    >
                      Category
                    </label>
                    <select
                      id="help-category"
                      value={category}
                      onChange={e => setCategory(e.target.value as SupportTicket['category'])}
                      className="w-full bg-[#1e1e1e] border border-[#404040] rounded px-3 py-2 text-white text-sm focus:border-blue-500 focus:outline-none"
                    >
                      <option value="question">{categoryIcons.question} Question</option>
                      <option value="bug">{categoryIcons.bug} Bug Report</option>
                      <option value="feature">{categoryIcons.feature} Feature Request</option>
                      <option value="documentation">
                        {categoryIcons.documentation} Documentation
                      </option>
                    </select>
                  </div>

                  <div>
                    <label
                      htmlFor="help-priority"
                      className="block text-xs font-medium text-gray-300 mb-2"
                    >
                      Priority
                    </label>
                    <select
                      id="help-priority"
                      value={priority}
                      onChange={e => setPriority(e.target.value as SupportTicket['priority'])}
                      className="w-full bg-[#1e1e1e] border border-[#404040] rounded px-3 py-2 text-white text-sm focus:border-blue-500 focus:outline-none"
                    >
                      <option value="low">Low</option>
                      <option value="medium">Medium</option>
                      <option value="high">High</option>
                      <option value="critical">Critical</option>
                    </select>
                  </div>
                </div>

                {/* Subject */}
                <div>
                  <label
                    htmlFor="help-subject"
                    className="block text-xs font-medium text-gray-300 mb-2"
                  >
                    Subject *
                  </label>
                  <input
                    id="help-subject"
                    type="text"
                    value={subject}
                    onChange={e => setSubject(e.target.value)}
                    placeholder="Brief description of your issue or question"
                    className="w-full bg-[#1e1e1e] border border-[#404040] rounded px-3 py-2 text-white text-sm placeholder-gray-500 focus:border-blue-500 focus:outline-none"
                    maxLength={100}
                  />
                  <div className="text-xs text-gray-500 mt-1">{subject.length}/100 characters</div>
                </div>

                {/* Description */}
                <div>
                  <label
                    htmlFor="help-description"
                    className="block text-xs font-medium text-gray-300 mb-2"
                  >
                    Description *
                  </label>
                  <textarea
                    id="help-description"
                    value={description}
                    onChange={e => setDescription(e.target.value)}
                    placeholder="Please provide detailed information about your issue, including steps to reproduce if it's a bug..."
                    rows={6}
                    className="w-full bg-[#1e1e1e] border border-[#404040] rounded px-3 py-2 text-white text-sm placeholder-gray-500 focus:border-blue-500 focus:outline-none resize-none"
                    maxLength={2000}
                  />
                  <div className="text-xs text-gray-500 mt-1">
                    {description.length}/2000 characters
                  </div>
                </div>

                {/* File Attachments */}
                <div>
                  <label
                    htmlFor="help-attachments"
                    className="block text-xs font-medium text-gray-300 mb-2"
                  >
                    Attachments (Screenshots, Logs, etc.)
                  </label>

                  <div className="space-y-3">
                    {/* Attachment List */}
                    {attachments.length > 0 && (
                      <div className="space-y-2">
                        {attachments.map((file, index) => {
                          const FileIcon = getFileIcon(file);
                          return (
                            <div
                              key={`${file.name}-${index}`}
                              className="flex items-center justify-between bg-[#1e1e1e] border border-[#404040] rounded px-3 py-2"
                            >
                              <div className="flex items-center gap-3 min-w-0">
                                <FileIcon className="w-4 h-4 text-blue-400 flex-shrink-0" />
                                <div className="min-w-0">
                                  <div className="text-sm text-white truncate">{file.name}</div>
                                  <div className="text-xs text-gray-500">
                                    {formatFileSize(file.size)}
                                  </div>
                                </div>
                              </div>
                              <button
                                onClick={() => removeAttachment(index)}
                                className="p-1 text-gray-400 hover:text-red-400 hover:bg-[#3d3d3d] rounded transition-colors flex-shrink-0"
                                aria-label={`Remove ${file.name}`}
                              >
                                <X className="w-4 h-4" />
                              </button>
                            </div>
                          );
                        })}
                      </div>
                    )}

                    {/* Add Attachment Button */}
                    <button
                      type="button"
                      onClick={() => fileInputRef.current?.click()}
                      className="w-full border-2 border-dashed border-[#404040] rounded-lg p-4 text-gray-400 hover:text-gray-300 hover:border-[#505050] transition-colors"
                    >
                      <div className="flex flex-col items-center gap-2">
                        <Paperclip className="w-5 h-5" />
                        <span className="text-sm">
                          Click to attach files (screenshots, logs, documents)
                        </span>
                        <span className="text-xs text-gray-500">
                          Max 10MB per file • PNG, JPG, PDF, TXT, LOG supported
                        </span>
                      </div>
                    </button>

                    {/* Hidden File Input */}
                    <input
                      id="help-attachments"
                      ref={fileInputRef}
                      type="file"
                      multiple
                      accept=".png,.jpg,.jpeg,.pdf,.txt,.log,.json,.xml,.csv"
                      onChange={handleFileSelect}
                      className="hidden"
                    />
                  </div>
                </div>

                {/* Error Message */}
                {errorMessage && (
                  <div className="flex items-center gap-2 p-3 bg-red-500/10 border border-red-500/20 rounded text-red-400 text-sm">
                    <AlertCircle className="w-4 h-4 flex-shrink-0" />
                    {errorMessage}
                  </div>
                )}
              </div>
            </form>
          )}
        </div>

        {/* Footer */}
        {sendStatus !== 'success' && (
          <div className="flex items-center justify-between p-4 border-t border-[#404040] bg-[#252526]">
            <div className="flex items-center gap-2">
              <Mail className="w-4 h-4 text-gray-400" />
              <span className="text-xs text-gray-400">
                Sent to: plc-gbt-support@whiskeyhouse.com
              </span>
            </div>

            <div className="flex items-center gap-3">
              <button
                onClick={onClose}
                className="px-4 py-2 text-gray-400 hover:text-white transition-colors"
                disabled={isSending}
              >
                Cancel
              </button>

              <button
                onClick={handleSendSupport}
                disabled={isSending || !subject.trim() || !description.trim()}
                className={cn(
                  'flex items-center gap-2 px-4 py-2 rounded transition-colors',
                  isSending || !subject.trim() || !description.trim()
                    ? 'bg-gray-600 text-gray-400 cursor-not-allowed'
                    : 'bg-blue-600 text-white hover:bg-blue-700'
                )}
              >
                {isSending ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                    Sending...
                  </>
                ) : (
                  <>
                    <Send className="w-4 h-4" />
                    Send Support Request
                  </>
                )}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>,
    document.body
  );
}
