version: '3.8'

services:
  theia:
    image: theiaide/theia:latest
    container_name: plc-gbt-theia
    ports:
      - '3100:3000'
    environment:
      - THEIA_MINIMAP=false
      - THEIA_HOST=0.0.0.0
      - THEIA_PORT=3000
      - GIT_AUTHOR_NAME
      - GIT_AUTHOR_EMAIL
      - GIT_COMMITTER_NAME
      - GIT_COMMITTER_EMAIL
    working_dir: /home/project
    volumes:
      - ../..:/home/project:cached
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
