/**
 * EXAMPLE: OpenAPI MCP Generated Control Loop Schemas
 *
 * This file demonstrates what properly generated schemas would look like
 * when using OpenAPI Schema MCP from MCP_Docker following the AI Task Orchestrator methodology.
 *
 * 🔗 Generated by: MCP_Docker OpenAPI tools
 * 📋 Source: OpenAPI 3.0.3 specification
 * ✅ Methodology: AI Task Orchestrator compliant
 */

import { z } from 'zod';

// ===== MCP-GENERATED SCHEMAS (Example) =====
// These would be automatically generated from OpenAPI spec via MCP_Docker

/**
 * TuningQueueEntry schema generated from OpenAPI MCP
 *
 * @description Represents a control loop entry in the tuning queue
 * @source OpenAPI spec: #/components/schemas/TuningQueueEntry
 */
export const TuningQueueEntrySchema = z
  .object({
    /** Unique identifier for the control loop */
    loopId: z
      .string()
      .regex(
        /^[a-zA-Z0-9_-]+$/,
        'Loop ID must contain only alphanumeric characters, underscores, and dashes'
      ),

    /** Display name for the loop */
    loopName: z
      .string()
      .min(1, 'Loop name is required')
      .max(100, 'Loop name cannot exceed 100 characters'),

    /** Position in tuning queue (unique within queue) */
    queID: z.number().int('Queue ID must be an integer').min(1, 'Queue ID must be positive'),

    /** Whether this loop is currently in focus */
    isFocus: z.boolean(),

    /** Whether AI analysis is currently running */
    analysisOngoing: z.boolean(),

    /** Duration of analysis in seconds (optional) */
    analysisTime: z
      .number()
      .int('Analysis time must be an integer')
      .min(30, 'Analysis time must be at least 30 seconds')
      .max(3600, 'Analysis time cannot exceed 1 hour')
      .optional(),

    /** Whether auto-tune functionality is enabled */
    autotuneEnable: z.boolean(),

    /** When the loop was added to the queue */
    queuedAt: z.string().datetime('Invalid date-time format'),

    /** Last time queue entry was modified */
    lastModified: z.string().datetime('Invalid date-time format'),

    /** Reference to original loop data */
    originalLoopData: z.lazy(() => ControlLoopSummarySchema),
  })
  .strict();

/**
 * FocusLoopEditableParameters schema generated from OpenAPI MCP
 *
 * @description Editable parameters for the focus loop in tuning interface
 * @source OpenAPI spec: #/components/schemas/FocusLoopEditableParameters
 */
export const FocusLoopEditableParametersSchema = z
  .object({
    /** SP - Target process value */
    setpoint: z
      .number()
      .min(-9999, 'Setpoint cannot be less than -9999')
      .max(9999, 'Setpoint cannot exceed 9999'),

    /** CV - Control variable/output value */
    controlOutput: z
      .number()
      .min(0, 'Control output cannot be negative')
      .max(100, 'Control output cannot exceed 100%'),

    /** Kp or Kc - Proportional gain */
    proportionalGain: z
      .number()
      .min(0.001, 'Proportional gain must be positive')
      .max(999.9, 'Proportional gain cannot exceed 999.9'),

    /** Ki or Ti - Integral gain/time */
    integralGain: z
      .number()
      .min(0.001, 'Integral gain must be positive')
      .max(999.9, 'Integral gain cannot exceed 999.9'),

    /** Kd or Td - Derivative gain/time */
    derivativeGain: z
      .number()
      .min(0, 'Derivative gain cannot be negative')
      .max(999.9, 'Derivative gain cannot exceed 999.9'),

    /** When parameters were last modified */
    lastUpdated: z.string().datetime('Invalid date-time format'),

    /** Source of last modification */
    modifiedBy: z.enum(['user', 'ai', 'auto']),
  })
  .strict();

/**
 * ControlLoopSummary schema generated from OpenAPI MCP
 *
 * @description Summary information for control loop cards
 * @source OpenAPI spec: #/components/schemas/ControlLoopSummary
 */
export const ControlLoopSummarySchema = z
  .object({
    id: z.string(),
    name: z.string(),
    type: z.enum([
      'ladder_logic_standard_pid',
      'ladder_logic_advanced_pid',
      'function_block_standard_pide',
      'function_block_advanced_pide',
    ]),
    status: z.enum(['running', 'stopped', 'error', 'tuning', 'manual', 'cascade']),
    setpoint: z.number(),
    process_value: z.number(),
    control_output: z.number(),
    mode: z.enum(['Manual', 'Automatic', 'Cascade', 'Override', 'Program', 'Ratio']),
    performance_score: z.number().min(0).max(100),
    alarms_active: z.number().int().min(0),
    last_updated: z.string().datetime('Invalid date-time format'),
  })
  .strict();

/**
 * TuningQueueState schema generated from OpenAPI MCP
 *
 * @description Complete state of the tuning queue
 * @source OpenAPI spec: #/components/schemas/TuningQueueState
 */
export const TuningQueueStateSchema = z
  .object({
    /** All entries in the tuning queue */
    entries: z.array(TuningQueueEntrySchema),

    /** ID of currently focused loop */
    focusLoopId: z.string().nullable(),

    /** Maximum allowed queue size */
    maxQueueSize: z.number().int().min(1).max(50),

    /** Next available queue ID */
    nextAvailableQueID: z.number().int().min(1),

    /** When queue was last modified */
    lastUpdated: z.string().datetime('Invalid date-time format'),
  })
  .strict();

/**
 * TuningQueueContextAction enum generated from OpenAPI MCP
 *
 * @description Available actions in context popup
 * @source OpenAPI spec: #/components/schemas/TuningQueueContextAction
 */
export const TuningQueueContextActionSchema = z.enum([
  'change_queue_id',
  'set_to_active',
  'remove_from_queue',
  'start_loop_analysis',
  'stop_loop_analysis',
]);

/**
 * ControlLoopOperatingMode enum generated from OpenAPI MCP
 *
 * @description Control loop operating modes for Quick Actions dropdown
 * @source OpenAPI spec: #/components/schemas/ControlLoopOperatingMode
 */
export const ControlLoopOperatingModeSchema = z.enum(['Auto', 'Manual', 'Software Manual', 'Off']);

/**
 * AdvancedSettingsConfiguration schema generated from OpenAPI MCP
 *
 * @description Configuration for Advanced Settings modal
 * @source OpenAPI spec: #/components/schemas/AdvancedSettingsConfiguration
 */
export const AdvancedSettingsConfigurationSchema = z
  .object({
    autotuneEnable: z.boolean(),
    analysisTime: z.number().int().min(30).max(3600),
    tuningAlgorithm: z.enum([
      'manual',
      'ziegler_nichols',
      'cohen_coon',
      'internal_model_control',
      'lambda_tuning',
      'pid_autotune',
    ]),
    safetyLimits: z.lazy(() => SafetyLimitsConfigSchema),
    historicalDataRetention: z.number().int().min(1).max(365),
    autoSaveInterval: z.number().int().min(1000).max(300000),
  })
  .strict();

/**
 * SafetyLimitsConfig schema generated from OpenAPI MCP
 *
 * @description Safety limits configuration
 * @source OpenAPI spec: #/components/schemas/SafetyLimitsConfig
 */
export const SafetyLimitsConfigSchema = z
  .object({
    maxSetpointChange: z.number().min(0.001).max(1000),
    maxOutputChange: z.number().min(0.001).max(100),
    emergencyShutdownThreshold: z.number().min(0.001),
    parameterChangeRateLimit: z.number().min(0.001).max(10),
  })
  .strict();

// ===== MCP-GENERATED TYPES =====
// TypeScript types automatically inferred from OpenAPI MCP schemas

export type TuningQueueEntry = z.infer<typeof TuningQueueEntrySchema>;
export type FocusLoopEditableParameters = z.infer<typeof FocusLoopEditableParametersSchema>;
export type ControlLoopSummary = z.infer<typeof ControlLoopSummarySchema>;
export type TuningQueueState = z.infer<typeof TuningQueueStateSchema>;
export type TuningQueueContextAction = z.infer<typeof TuningQueueContextActionSchema>;
export type ControlLoopOperatingMode = z.infer<typeof ControlLoopOperatingModeSchema>;
export type AdvancedSettingsConfiguration = z.infer<typeof AdvancedSettingsConfigurationSchema>;
export type SafetyLimitsConfig = z.infer<typeof SafetyLimitsConfigSchema>;

// ===== MCP-GENERATED API CLIENT =====
// API client with type-safe methods generated from OpenAPI spec

export const controlLoopApi = {
  /**
   * Get tuning queue entries
   * @source GET /api/v1/tuning-queue
   */
  getTuningQueue: async (): Promise<TuningQueueState> => {
    const response = await fetch('/api/v1/tuning-queue');
    const data = await response.json();
    return TuningQueueStateSchema.parse(data);
  },

  /**
   * Add loop to tuning queue
   * @source POST /api/v1/tuning-queue
   */
  addToTuningQueue: async (entry: TuningQueueEntry): Promise<TuningQueueEntry> => {
    // Validate request with OpenAPI MCP schema
    const validatedEntry = TuningQueueEntrySchema.parse(entry);

    const response = await fetch('/api/v1/tuning-queue', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(validatedEntry),
    });

    const data = await response.json();
    // Validate response with OpenAPI MCP schema
    return TuningQueueEntrySchema.parse(data);
  },

  /**
   * Get focus loop parameters
   * @source GET /api/v1/tuning-queue/{loopId}/parameters
   */
  getFocusLoopParameters: async (loopId: string): Promise<FocusLoopEditableParameters> => {
    const response = await fetch(`/api/v1/tuning-queue/${loopId}/parameters`);
    const data = await response.json();
    return FocusLoopEditableParametersSchema.parse(data);
  },

  /**
   * Update focus loop parameters
   * @source PUT /api/v1/tuning-queue/{loopId}/parameters
   */
  updateFocusLoopParameters: async (
    loopId: string,
    parameters: FocusLoopEditableParameters
  ): Promise<FocusLoopEditableParameters> => {
    // Validate request with OpenAPI MCP schema
    const validatedParams = FocusLoopEditableParametersSchema.parse(parameters);

    const response = await fetch(`/api/v1/tuning-queue/${loopId}/parameters`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(validatedParams),
    });

    const data = await response.json();
    // Validate response with OpenAPI MCP schema
    return FocusLoopEditableParametersSchema.parse(data);
  },
};

// ===== COMPARISON WITH MANUAL APPROACH =====

/**
 * ✅ OpenAPI MCP Advantages Demonstrated:
 *
 * 1. **Single Source of Truth**: All schemas derived from OpenAPI spec
 * 2. **Type Safety**: Strict object validation with `.strict()`
 * 3. **Format Validation**: Proper datetime, regex, enum validation
 * 4. **Documentation**: JSDoc comments auto-generated from OpenAPI descriptions
 * 5. **API Integration**: Type-safe API client with request/response validation
 * 6. **Consistency**: Standardized error messages and validation rules
 * 7. **Maintainability**: Changes to OpenAPI spec automatically propagate
 * 8. **Production Ready**: Runtime validation for all API interactions
 *
 * ❌ Manual Schema Issues Resolved:
 *
 * 1. No more `z.record(z.unknown())` linter errors
 * 2. No schema drift between frontend/backend
 * 3. No manual maintenance of duplicate definitions
 * 4. No missing validation rules
 * 5. No inconsistent error messages
 * 6. No bypassing of AI Task Orchestrator methodology
 */

export const mcpGeneratedSchemas = {
  TuningQueueEntrySchema,
  FocusLoopEditableParametersSchema,
  ControlLoopSummarySchema,
  TuningQueueStateSchema,
  TuningQueueContextActionSchema,
  ControlLoopOperatingModeSchema,
  AdvancedSettingsConfigurationSchema,
  SafetyLimitsConfigSchema,
};

export const mcpGeneratedApi = controlLoopApi;
