/**
 * 🏛️ MCP-Governed Control Loop Schemas
 *
 * This file demonstrates the transition from manual schema creation to
 * OpenAPI Schema MCP governance following AI Task Orchestrator methodology.
 *
 * 🔗 Generated by: MCP_Docker OpenAPI tools (when available)
 * 📋 Source: comprehensive-openapi-governance.json
 * ✅ Methodology: AI Task Orchestrator compliant
 *
 * NOTE: This is a transitional implementation. Once MCP_Docker is available,
 * this file should be replaced with actual MCP-generated schemas.
 */

import { z } from 'zod';

// ===== TRANSITION NOTICE =====
// These schemas follow the exact structure defined in comprehensive-openapi-governance.json
// They will be replaced with actual MCP-generated schemas when MCP_Docker is available

/**
 * Engineering Units enumeration from OpenAPI MCP
 * @source #/components/schemas/EngineeringUnits
 */
export const EngineeringUnitsSchema = z.enum([
  'Percent',
  'PSI',
  'Bar',
  'Celsius',
  'Fahrenheit',
  'Kelvin',
  'GPM',
  'M3/H',
  'LBS/H',
  'KG/H',
  'Volts',
  'mA',
]);

/**
 * Control Loop Type enumeration from OpenAPI MCP
 * @source #/components/schemas/ControlLoopType
 */
export const ControlLoopTypeSchema = z.enum([
  'ladder_logic_standard_pid',
  'ladder_logic_advanced_pid',
  'function_block_standard_pide',
  'function_block_advanced_pide',
]);

/**
 * Control Loop Status enumeration from OpenAPI MCP
 * @source #/components/schemas/ControlLoopStatus
 */
export const ControlLoopStatusSchema = z.enum([
  'running',
  'stopped',
  'error',
  'tuning',
  'manual',
  'cascade',
]);

/**
 * Control Mode enumeration from OpenAPI MCP
 * @source #/components/schemas/ControlMode
 */
export const ControlModeSchema = z.enum([
  'Manual',
  'Automatic',
  'Cascade',
  'Override',
  'Program',
  'Ratio',
]);

/**
 * Process Variable schema from OpenAPI MCP
 * @source #/components/schemas/ProcessVariable
 */
export const ProcessVariableSchema = z
  .object({
    tag_name: z
      .string()
      .regex(/^[A-Za-z][A-Za-z0-9_]*$/, 'Tag name must follow PLC naming conventions')
      .min(1, 'Tag name is required')
      .max(40, 'Tag name cannot exceed 40 characters'),
    engineering_units: EngineeringUnitsSchema,
    range_min: z.number(),
    range_max: z.number(),
    current_value: z.number().optional(),
    quality: z.enum(['good', 'bad', 'uncertain']).default('good'),
    timestamp: z.string().datetime().optional(),
  })
  .refine(data => data.range_max > data.range_min, {
    message: 'Range max must be greater than range min',
    path: ['range_max'],
  })
  .strict();

/**
 * PID Parameters schema from OpenAPI MCP
 * @source #/components/schemas/PIDParameters
 */
export const PIDParametersSchema = z
  .object({
    proportional_gain: z
      .number()
      .min(0.001, 'Proportional gain must be positive')
      .max(999.9, 'Proportional gain cannot exceed 999.9'),
    integral_time: z
      .number()
      .min(0.01, 'Integral time must be at least 0.01 minutes')
      .max(9999.0, 'Integral time cannot exceed 9999 minutes'),
    derivative_time: z
      .number()
      .min(0.0, 'Derivative time cannot be negative')
      .max(99.99, 'Derivative time cannot exceed 99.99 minutes'),
    integral_hold: z.boolean().default(false),
    derivative_hold: z.boolean().default(false),
    feedforward_gain: z.number().min(0.0).max(10.0).optional(),
  })
  .strict();

/**
 * Control Loop Summary schema from OpenAPI MCP
 * @source #/components/schemas/ControlLoopSummary
 */
export const ControlLoopSummarySchema = z
  .object({
    id: z.string().regex(/^[a-zA-Z0-9_-]+$/, 'Invalid loop ID format'),
    name: z.string().min(1, 'Name is required').max(200, 'Name cannot exceed 200 characters'),
    type: ControlLoopTypeSchema,
    status: ControlLoopStatusSchema,
    setpoint: z.number(),
    process_value: z.number(),
    control_output: z.number().min(0).max(100),
    mode: ControlModeSchema,
    performance_score: z.number().min(0).max(100),
    alarms_active: z.number().int().min(0),
    last_updated: z.string().datetime(),
  })
  .strict();

/**
 * Enhanced Control Loop schema from OpenAPI MCP
 * @source #/components/schemas/EnhancedControlLoop
 */
export const EnhancedControlLoopSchema = z
  .object({
    id: z.string().regex(/^[a-zA-Z0-9_-]+$/),
    tag_name: z
      .string()
      .regex(/^[A-Za-z][A-Za-z0-9_]*$/)
      .min(1)
      .max(40),
    name: z.string().min(1).max(200),
    description: z.string().max(500).optional(),
    type: ControlLoopTypeSchema,
    control_mode: ControlModeSchema,
    process_variable: ProcessVariableSchema,
    pid_parameters: PIDParametersSchema,
    enabled: z.boolean(),
    status: ControlLoopStatusSchema,
    scan_time: z.number().min(0.001).max(60.0),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime(),
    version: z.string().regex(/^\d+\.\d+\.\d+$/),
    schema_version: z.string().regex(/^\d{2}\.\d{2}\.\d{3}$/),
  })
  .strict();

/**
 * Tuning Queue Entry schema from OpenAPI MCP
 * @source #/components/schemas/TuningQueueEntry
 */
export const TuningQueueEntrySchema = z
  .object({
    loopId: z
      .string()
      .regex(
        /^[a-zA-Z0-9_-]+$/,
        'Loop ID must contain only alphanumeric characters, underscores, and dashes'
      ),
    loopName: z
      .string()
      .min(1, 'Loop name is required')
      .max(100, 'Loop name cannot exceed 100 characters'),
    queID: z.number().int().min(1, 'Queue ID must be positive'),
    isFocus: z.boolean(),
    analysisOngoing: z.boolean(),
    analysisTime: z
      .number()
      .int()
      .min(30, 'Analysis time must be at least 30 seconds')
      .max(3600, 'Analysis time cannot exceed 1 hour')
      .optional(),
    autotuneEnable: z.boolean(),
    queuedAt: z.string().datetime(),
    lastModified: z.string().datetime(),
    originalLoopData: ControlLoopSummarySchema,
  })
  .strict();

/**
 * Focus Loop Editable Parameters schema from OpenAPI MCP
 * @source #/components/schemas/FocusLoopEditableParameters
 */
export const FocusLoopEditableParametersSchema = z
  .object({
    setpoint: z
      .number()
      .min(0, 'Setpoint cannot be negative')
      .max(9999, 'Setpoint cannot exceed 9999'),
    controlOutput: z
      .number()
      .min(0, 'Control output cannot be negative')
      .max(100, 'Control output cannot exceed 100%'),
    proportionalGain: z
      .number()
      .min(0, 'Proportional gain cannot be negative')
      .max(999.9, 'Proportional gain cannot exceed 999.9'),
    integralGain: z
      .number()
      .min(0, 'Integral gain cannot be negative')
      .max(999.9, 'Integral gain cannot exceed 999.9'),
    derivativeGain: z
      .number()
      .min(0, 'Derivative gain cannot be negative')
      .max(999.9, 'Derivative gain cannot exceed 999.9'),
    lastUpdated: z.string().datetime(),
    modifiedBy: z.enum(['user', 'ai', 'auto']),
  })
  .strict();

/**
 * Tuning Queue State schema from OpenAPI MCP
 * @source #/components/schemas/TuningQueueState
 */
export const TuningQueueStateSchema = z
  .object({
    entries: z.array(TuningQueueEntrySchema),
    focusLoopId: z.string().nullable(),
    maxQueueSize: z.number().int().min(1).max(50),
    nextAvailableQueID: z.number().int().min(1),
    lastUpdated: z.string().datetime(),
  })
  .strict();

/**
 * Tuning Queue Context Action schema from OpenAPI MCP
 * @source #/components/schemas/TuningQueueContextAction
 */
export const TuningQueueContextActionSchema = z.enum([
  'change_queue_id',
  'set_to_active',
  'remove_from_queue',
  'start_loop_analysis',
  'stop_loop_analysis',
]);

/**
 * Control Loop Operating Mode schema from OpenAPI MCP
 * @source #/components/schemas/ControlLoopOperatingMode
 */
export const ControlLoopOperatingModeSchema = z.enum(['Auto', 'Manual', 'Software Manual', 'Off']);

/**
 * WebSocket Event Type schema from OpenAPI MCP
 * @source #/components/schemas/WebSocketEventType
 */
export const WebSocketEventTypeSchema = z.enum([
  'control_loop_update',
  'tuning_queue_update',
  'parameter_change',
  'analysis_start',
  'analysis_complete',
  'mode_change',
  'error_occurred',
  'connection_status',
]);

/**
 * WebSocket Event schema from OpenAPI MCP
 * @source #/components/schemas/WebSocketEvent
 */
export const WebSocketEventSchema = z
  .object({
    type: WebSocketEventTypeSchema,
    timestamp: z.string().datetime(),
    loopId: z
      .string()
      .regex(/^[a-zA-Z0-9_-]+$/)
      .optional(),
    data: z.record(z.string(), z.unknown()),
    source: z.enum(['user', 'ai', 'websocket', 'system']).optional(),
  })
  .strict();

/**
 * Keyboard Navigation State schema from OpenAPI MCP
 * @source #/components/schemas/KeyboardNavigationState
 */
export const KeyboardNavigationStateSchema = z
  .object({
    isNavigationActive: z.boolean(),
    currentIndex: z.number().int().min(0),
    totalEntries: z.number().int().min(0),
    navigationMode: z.enum(['queue', 'parameters']),
  })
  .strict();

/**
 * UI State schema from OpenAPI MCP
 * @source #/components/schemas/UIState
 */
export const UIStateSchema = z
  .object({
    currentView: z.enum(['dashboard', 'tuning_interface', 'settings', 'analytics']),
    tuningQueueState: TuningQueueStateSchema,
    navigationState: KeyboardNavigationStateSchema,
    sidebarExpanded: z.boolean().default(true),
    selectedFilters: z
      .object({
        status: z.array(ControlLoopStatusSchema).optional(),
        type: z.array(ControlLoopTypeSchema).optional(),
      })
      .optional(),
    lastUpdated: z.string().datetime(),
  })
  .strict();

/**
 * API Response schema from OpenAPI MCP
 * @source #/components/schemas/APIResponse
 */
export const APIResponseSchema = z
  .object({
    success: z.boolean(),
    data: z.unknown().optional(),
    error: z
      .object({
        code: z.string(),
        message: z.string(),
        details: z.record(z.string(), z.unknown()).optional(),
      })
      .optional(),
    timestamp: z.string().datetime(),
    pagination: z
      .object({
        page: z.number().int().min(1),
        limit: z.number().int().min(1).max(100),
        total: z.number().int().min(0),
        hasNext: z.boolean(),
        hasPrev: z.boolean(),
      })
      .optional(),
  })
  .strict();

// ===== TYPE EXPORTS =====
// TypeScript types inferred from OpenAPI MCP schemas

export type EngineeringUnits = z.infer<typeof EngineeringUnitsSchema>;
export type ControlLoopType = z.infer<typeof ControlLoopTypeSchema>;
export type ControlLoopStatus = z.infer<typeof ControlLoopStatusSchema>;
export type ControlMode = z.infer<typeof ControlModeSchema>;
export type ProcessVariable = z.infer<typeof ProcessVariableSchema>;
export type PIDParameters = z.infer<typeof PIDParametersSchema>;
export type ControlLoopSummary = z.infer<typeof ControlLoopSummarySchema>;
export type EnhancedControlLoop = z.infer<typeof EnhancedControlLoopSchema>;
export type TuningQueueEntry = z.infer<typeof TuningQueueEntrySchema>;
export type FocusLoopEditableParameters = z.infer<typeof FocusLoopEditableParametersSchema>;
export type TuningQueueState = z.infer<typeof TuningQueueStateSchema>;
export type TuningQueueContextAction = z.infer<typeof TuningQueueContextActionSchema>;
export type ControlLoopOperatingMode = z.infer<typeof ControlLoopOperatingModeSchema>;
export type WebSocketEventType = z.infer<typeof WebSocketEventTypeSchema>;
export type WebSocketEvent = z.infer<typeof WebSocketEventSchema>;
export type KeyboardNavigationState = z.infer<typeof KeyboardNavigationStateSchema>;
export type UIState = z.infer<typeof UIStateSchema>;
export type APIResponse = z.infer<typeof APIResponseSchema>;

// ===== SCHEMA COLLECTIONS =====
// Organized collections for easier import

export const MCPControlLoopSchemas = {
  ControlLoopSummarySchema,
  EnhancedControlLoopSchema,
  ControlLoopTypeSchema,
  ControlLoopStatusSchema,
  ControlModeSchema,
  ProcessVariableSchema,
  PIDParametersSchema,
} as const;

export const MCPTuningInterfaceSchemas = {
  TuningQueueEntrySchema,
  TuningQueueStateSchema,
  FocusLoopEditableParametersSchema,
  TuningQueueContextActionSchema,
  ControlLoopOperatingModeSchema,
  KeyboardNavigationStateSchema,
} as const;

export const MCPWebSocketSchemas = {
  WebSocketEventSchema,
  WebSocketEventTypeSchema,
} as const;

export const MCPUISchemas = {
  UIStateSchema,
  KeyboardNavigationStateSchema,
} as const;

export const MCPCoreSchemas = {
  APIResponseSchema,
  EngineeringUnitsSchema,
} as const;

// ===== MIGRATION STATUS =====
/**
 * 🔄 MIGRATION STATUS: Transitional Implementation
 *
 * Current Status:
 * ✅ OpenAPI specification complete (comprehensive-openapi-governance.json)
 * ✅ Schema structure matches OpenAPI MCP requirements
 * ✅ Strict validation with .strict() enforced
 * ✅ Complete type inference from schemas
 * ✅ JSDoc documentation from OpenAPI descriptions
 *
 * Next Steps:
 * 🔄 Replace with actual MCP_Docker generated schemas when available
 * 🔄 Implement API client with OpenAPI MCP governance
 * 🔄 Update all component imports to use these schemas
 * 🔄 Remove manual schema files (control-loop.schemas.ts)
 *
 * Benefits Achieved:
 * ✅ Single source of truth alignment
 * ✅ Eliminated z.record(z.unknown()) linter errors
 * ✅ Strict object validation
 * ✅ Complete type safety
 * ✅ AI Task Orchestrator methodology compliance
 */
