/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/node-properties/{nodeType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get node property schema
         * @description Retrieve the property schema for a specific industrial node type
         */
        get: operations["getNodePropertySchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-properties/{nodeType}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate node configuration
         * @description Validate a node configuration against its property schema
         */
        post: operations["validateNodeConfiguration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-properties/{nodeType}/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test node connection
         * @description Test the connection for a node configuration
         */
        post: operations["testNodeConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Industrial automation node types supported by the system
         * @enum {string}
         */
        IndustrialNodeType: "plc-input" | "plc-output" | "pid-controller" | "hmi-display" | "data-logger" | "alarm-handler" | "modbus-client" | "opc-server" | "opc-client" | "custom-logic" | "n8n-workflow" | "feedforward-controller" | "url-display" | "narx-neural-network" | "gaussian-process-regression" | "lstm-model" | "sindy-identifier" | "reinforcement-learning" | "mpc-controller" | "kalman-filter" | "quadratic-programming" | "subspace-identification" | "imc-controller" | "arx-armax-identifier" | "genetic-algorithm" | "recursive-least-squares" | "model-validation" | "pilco-pets" | "prbs-generator" | "relay-feedback-test" | "step-response-analyzer" | "distillation-simulator" | "performance-metrics" | "postgresql-connector" | "redis-connector" | "neo4j-connector" | "qdrant-connector" | "historian-connector" | "csv-dataset-creator" | "excel-dataset-creator" | "data-cleaner" | "feature-engineer" | "time-series-processor" | "math-function-creator" | "data-distribution-analyzer" | "dashboard-generator" | "pdf-report-generator" | "email-notifier" | "chart-generator" | "kpi-calculator" | "workflow-reference" | "workflow-subset" | "workflow-conditional" | "workflow-parallel" | "workflow-loop";
        /**
         * @description Supported property field types for dynamic form generation
         * @enum {string}
         */
        PropertyFieldType: "text" | "number" | "boolean" | "select" | "multiselect" | "textarea" | "json" | "password" | "url" | "email" | "slider" | "color" | "datetime" | "file";
        /**
         * @description Validation result severity levels
         * @enum {string}
         */
        ValidationSeverity: "error" | "warning" | "info";
        /**
         * @description UI width options for property fields
         * @enum {string}
         */
        PropertyFieldWidth: "full" | "half" | "third" | "quarter";
        /**
         * @description Types of connection tests available
         * @enum {string}
         */
        ConnectionTestType: "ping" | "modbus" | "opc" | "http" | "database" | "custom";
        PropertyConstraints: {
            /** @description Minimum value for numeric fields */
            min?: number;
            /** @description Maximum value for numeric fields */
            max?: number;
            /** @description Minimum length for string fields */
            minLength?: number;
            /** @description Maximum length for string fields */
            maxLength?: number;
            /** @description Regular expression pattern for validation */
            pattern?: string;
            /** @description Step value for numeric inputs */
            step?: number;
            /** @description Allowed values for enumerated fields */
            enum?: (string | number)[];
        };
        PropertyUIHints: {
            width?: components["schemas"]["PropertyFieldWidth"];
            /** @description Whether to display field inline */
            inline?: boolean;
            /** @description Whether field group is collapsible */
            collapsible?: boolean;
            /** @description Icon name for the field */
            icon?: string;
            /** @description Additional help text for the field */
            helpText?: string;
            /** @description Units to display with numeric fields */
            units?: string;
            /** @description Display format for the field */
            format?: string;
        };
        PropertyOption: {
            /** @description Option value */
            value: string | number | boolean;
            /** @description Display label for the option */
            label: string;
            /** @description Optional description for the option */
            description?: string;
            /** @description Whether the option is disabled */
            disabled?: boolean;
            /** @description Option group for categorization */
            group?: string;
        };
        PropertyField: {
            /** @description Unique identifier for the property field */
            key: string;
            /** @description Display label for the field */
            label: string;
            type: components["schemas"]["PropertyFieldType"];
            /** @description Help text describing the field */
            description?: string;
            /** @description Placeholder text for input fields */
            placeholder?: string;
            /** @description Default value for the field */
            defaultValue?: unknown;
            /** @description Whether the field is required */
            required?: boolean;
            /** @description Whether the field is read-only */
            readonly?: boolean;
            /** @description Whether the field is hidden */
            hidden?: boolean;
            /** @description Group ID this field belongs to */
            group?: string;
            /** @description Display order within the group */
            order?: number;
            /** @description Fields this field depends on */
            dependsOn?: string[];
            /** @description Options for select/multiselect fields */
            options?: components["schemas"]["PropertyOption"][];
            constraints?: components["schemas"]["PropertyConstraints"];
            ui?: components["schemas"]["PropertyUIHints"];
        };
        PropertyGroup: {
            /** @description Unique identifier for the property group */
            id: string;
            /** @description Display label for the group */
            label: string;
            /** @description Description of the group */
            description?: string;
            /** @description Icon name for the group */
            icon?: string;
            /** @description Whether the group can be collapsed */
            collapsible?: boolean;
            /** @description Whether the group is collapsed by default */
            defaultCollapsed?: boolean;
            /** @description Display order of the group */
            order?: number;
            /** @description Property fields in this group */
            fields: components["schemas"]["PropertyField"][];
        };
        ConnectionTest: {
            /** @description Unique identifier for the connection test */
            id: string;
            /** @description Display label for the test */
            label: string;
            /** @description Description of what the test validates */
            description?: string;
            type: components["schemas"]["ConnectionTestType"];
            /** @description Configuration fields required for this test */
            requiredFields: string[];
            /** @description Test timeout in milliseconds */
            timeoutMs: number;
        };
        PropertyTemplate: {
            /** @description Unique identifier for the template */
            id: string;
            /** @description Display label for the template */
            label: string;
            /** @description Description of the template */
            description: string;
            /** @description Template category */
            category: string;
            /** @description Template configuration values */
            config: {
                [key: string]: unknown;
            };
            /** @description Tags for template categorization */
            tags?: string[];
        };
        NodePropertySchema: {
            nodeType: components["schemas"]["IndustrialNodeType"];
            /** @description Schema version (semantic versioning) */
            version: string;
            /** @description Human-readable title for the node type */
            title: string;
            /** @description Detailed description of the node functionality */
            description: string;
            /** @description Property groups for organizing fields */
            groups: components["schemas"]["PropertyGroup"][];
            /** @description Available connection tests for this node type */
            connectionTests?: components["schemas"]["ConnectionTest"][];
            /** @description Pre-configured templates for this node type */
            templates?: components["schemas"]["PropertyTemplate"][];
        };
        ValidationResult: {
            /** @description Whether the validation passed */
            isValid: boolean;
            severity: components["schemas"]["ValidationSeverity"];
            /** @description Validation message */
            message: string;
            /** @description Field that failed validation */
            field: string;
            /** @description Error code for programmatic handling */
            code: string;
        };
        ConnectionTestResult: {
            /** @description Whether the connection test succeeded */
            success: boolean;
            /** @description Test result message */
            message: string;
            /** @description Additional test result details */
            details?: {
                [key: string]: unknown;
            };
            /** @description Connection latency in milliseconds */
            latencyMs?: number;
            /**
             * Format: date-time
             * @description When the test was performed
             */
            timestamp: string;
        };
        NodeConfigurationValidationRequest: {
            /** @description Node configuration to validate */
            configuration: {
                [key: string]: unknown;
            };
            /** @description Validation context information */
            context?: {
                workflowId?: string;
                nodeId?: string;
                connectedNodes?: string[];
            };
        };
        NodeConfigurationValidationResponse: {
            /** @description Whether validation passed overall */
            success: boolean;
            /** @description Overall validation message */
            message: string;
            /** @description Individual validation results */
            results: components["schemas"]["ValidationResult"][];
            /** @description Whether the configuration is valid */
            isValid: boolean;
            /** @description Validation errors */
            errors?: components["schemas"]["ValidationResult"][];
            /** @description Validation warnings */
            warnings?: components["schemas"]["ValidationResult"][];
        };
        NodeConnectionTestRequest: {
            /** @description ID of the connection test to run */
            testId: string;
            /** @description Node configuration for connection testing */
            configuration: {
                [key: string]: unknown;
            };
        };
        NodeConnectionTestResponse: {
            /** @description Whether the test request was processed */
            success: boolean;
            /** @description Test result message */
            message: string;
            result: components["schemas"]["ConnectionTestResult"];
        };
        ErrorResponse: {
            /** @description Error message */
            error: string;
            /** @description Additional error details */
            details?: string;
            /**
             * Format: date-time
             * @description Error timestamp
             */
            timestamp?: string;
            /** @description Error code for programmatic handling */
            code?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getNodePropertySchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of industrial node */
                nodeType: components["schemas"]["IndustrialNodeType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node property schema retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        data: components["schemas"]["NodePropertySchema"];
                    };
                };
            };
            /** @description Node type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validateNodeConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of industrial node */
                nodeType: components["schemas"]["IndustrialNodeType"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeConfigurationValidationRequest"];
            };
        };
        responses: {
            /** @description Configuration validation completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeConfigurationValidationResponse"];
                };
            };
            /** @description Invalid configuration data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    testNodeConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of industrial node */
                nodeType: components["schemas"]["IndustrialNodeType"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeConnectionTestRequest"];
            };
        };
        responses: {
            /** @description Connection test completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeConnectionTestResponse"];
                };
            };
        };
    };
}
