#!/bin/bash

# @git - Automated Git workflow script
# Usage: @git [optional-commit-message]
# If no message provided, generates context-specific commit message

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to log with colors
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Function to generate context-specific commit message
generate_commit_message() {
    local changed_files=$(git diff --cached --name-only)
    local num_files=$(echo "$changed_files" | wc -l)
    
    # Analyze file types and paths to generate meaningful message
    if echo "$changed_files" | grep -q "WorkflowPanel.tsx"; then
        echo "feat: enhance workflow monitor with persistence and view modes"
    elif echo "$changed_files" | grep -q "\.tsx\|\.ts" | head -1; then
        local main_file=$(echo "$changed_files" | grep "\.tsx\|\.ts" | head -1 | xargs basename)
        echo "feat: update ${main_file%.*} component implementation"
    elif echo "$changed_files" | grep -q "\.md"; then
        echo "docs: update documentation and guides"
    elif echo "$changed_files" | grep -q "package.json\|package-lock.json"; then
        echo "deps: update project dependencies"
    elif echo "$changed_files" | grep -q "\.sh\|\.py"; then
        echo "script: update automation and utility scripts"
    elif [ "$num_files" -gt 5 ]; then
        echo "feat: major codebase updates and improvements"
    else
        echo "feat: implement code improvements and fixes"
    fi
}

# Function to create error report
create_error_report() {
    local error_file="git-error-report-$(date +%Y%m%d_%H%M%S).md"
    cat > "$error_file" << EOF
# Git Automation Error Report

**Timestamp**: $(date)
**Working Directory**: $(pwd)
**Branch**: $(git branch --show-current 2>/dev/null || echo "unknown")

## Error Details

\`\`\`bash
$1
\`\`\`

## Git Status

\`\`\`
$(git status 2>&1 || echo "Git status failed")
\`\`\`

## Staged Changes

\`\`\`
$(git diff --cached --stat 2>&1 || echo "No staged changes")
\`\`\`

## Recent Commits

\`\`\`
$(git log --oneline -5 2>&1 || echo "No commit history")
\`\`\`

## Suggested Actions

1. Review the error message above
2. Check if files need to be staged: \`git add .\`
3. Verify branch permissions: \`git push -u origin \$(git branch --show-current)\`
4. Check for merge conflicts: \`git status\`
5. Ensure remote is properly configured: \`git remote -v\`

## Quick Recovery Commands

\`\`\`bash
# Reset if needed
git reset --soft HEAD~1

# Re-stage files
git add .

# Try manual commit
git commit -m "manual: fix and commit changes"

# Push with upstream
git push -u origin \$(git branch --show-current)
\`\`\`

---
*Generated by @git automation script*
EOF
    
    echo "$error_file"
}

# Main execution
main() {
    log_info "Starting @git automation workflow..."
    
    # Change to project root if not already there
    if [ ! -d ".git" ]; then
        log_info "Not in git root, attempting to find project root..."
        cd "$(git rev-parse --show-toplevel 2>/dev/null)" || {
            log_error "Not in a git repository!"
            exit 1
        }
    fi
    
    log_info "Working in: $(pwd)"
    log_info "Current branch: $(git branch --show-current)"
    
    # Save any work (this is a safety step, files should already be saved)
    log_info "Ensuring work is saved..."
    
    # Check for uncommitted changes
    if git diff --quiet && git diff --cached --quiet; then
        log_warning "No changes detected to commit"
        echo "success"
        exit 0
    fi
    
    # Stage all changes
    log_info "Staging all changes..."
    if ! git add . 2>/dev/null; then
        error_msg="Failed to stage changes: $(git add . 2>&1)"
        error_file=$(create_error_report "$error_msg")
        log_error "Staging failed. Error report: $error_file"
        exit 1
    fi
    
    # Check if there are staged changes
    if git diff --cached --quiet; then
        log_warning "No staged changes after git add"
        echo "success"
        exit 0
    fi
    
    # Generate or use provided commit message
    if [ -n "$1" ]; then
        commit_message="$1"
        log_info "Using provided commit message: $commit_message"
    else
        commit_message=$(generate_commit_message)
        log_info "Generated commit message: $commit_message"
    fi
    
    # Show what will be committed
    log_info "Files to be committed:"
    git diff --cached --name-only | sed 's/^/  - /'
    
    # Commit changes
    log_info "Committing changes..."
    if ! git commit -m "$commit_message" 2>/dev/null; then
        error_msg="Failed to commit changes: $(git commit -m "$commit_message" 2>&1)"
        error_file=$(create_error_report "$error_msg")
        log_error "Commit failed. Error report: $error_file"
        exit 1
    fi
    
    # Push to remote
    log_info "Pushing to remote..."
    current_branch=$(git branch --show-current)
    
    # Try to push, set upstream if needed
    if ! git push 2>/dev/null; then
        log_info "Initial push failed, trying with upstream..."
        if ! git push -u origin "$current_branch" 2>/dev/null; then
            error_msg="Failed to push to remote: $(git push -u origin "$current_branch" 2>&1)"
            error_file=$(create_error_report "$error_msg")
            log_error "Push failed. Error report: $error_file"
            exit 1
        fi
    fi
    
    # Verify push was successful
    log_info "Verifying push..."
    if ! git ls-remote --exit-code origin "$current_branch" >/dev/null 2>&1; then
        error_msg="Push verification failed - branch not found on remote"
        error_file=$(create_error_report "$error_msg")
        log_error "Push verification failed. Error report: $error_file"
        exit 1
    fi
    
    # All successful
    log_success "All operations completed successfully!"
    log_success "Committed: $commit_message"
    log_success "Pushed to: origin/$current_branch"
    
    echo "success"
}

# Execute main function with all arguments
main "$@"
